### ISSUE TITLE
Upgrade sites to Universal Analytics

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-metrics#6]
We will need to update the GA tracking snippet in each of these sites from the 'Classic' snippet to the 'Universal Analytics' snippet.

webmaker.org and subdomains:
- [ ] webmaker.org
- [ ] popcorn.w.o
- [ ] thimble.w.o
- [ ] events.w.o
- [ ] blog.w.o
- [ ] apps.w.o
- [ ] goggles.w.o
- [ ] welcome.w.o

Other domains and published pages (maybe static and hard to regenerate)
- [ ] *.makes.org (the profiles)
- [ ] *.makes.org (the makes)
- [ ] *.appalot.me

BSD:
- [ ] sendto.m.o

**Comment by adamlofting** [comment]
Note from GA

> You must transfer your property to Universal Analytics before retagging your site with analytics.js 

The upgrade process is currently in progress.

**Comment by adamlofting** [comment]
For sendto, we'll need to 
- [ ] update the ecommerce tracking tags on the thank you page:
  https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs

**Comment by adamlofting** [comment]
Cross-domain tracking requires deploying all the sites simultaneously(ish).
https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs#cross-domain

I'm not sure if/how we can make this changes to makes.org/appalot.me published content or if the effort is worthwhile at this point.

**Comment by adamlofting** [comment]
PRs to submit after account it upgraded:
- https://github.com/adamlofting/webmaker.org/
- https://github.com/adamlofting/popcorn.webmaker.org
- https://github.com/adamlofting/thimble.webmaker.org
- https://github.com/adamlofting/webmaker-events-2
- [x] need to find canonical source for blog.w.o source code (can update directly in the admin interface)
- https://github.com/adamlofting/appmaker
- https://github.com/adamlofting/goggles.webmaker.org
- https://github.com/mozilla/webmaker-landing-pages/

**Comment by adamlofting** [comment]
All webmaker.org subdomains ready to go.

**Comment by adamlofting** [comment]
GA account is upgraded

**Comment by adamlofting** [comment]
PRs:
@jbuck could you R? these and then we can work through deploy?
- https://github.com/mozilla/webmaker.org/pull/1334
- https://github.com/mozilla/popcorn.webmaker.org/pull/594
- https://github.com/mozilla/thimble.webmaker.org/pull/470
- https://github.com/mozilla/webmaker-events-2/pull/237
- https://github.com/mozilla-appmaker/appmaker/pull/2403
- https://github.com/mozilla/goggles.webmaker.org/pull/196
- https://github.com/mozilla/webmaker-landing-pages/pull/129

**Comment by jbuck** [comment]
@adamlofting I think we need to add some more PRs:
- https://github.com/mozilla/make-valet/blob/00cec78db6214e75456298578abffce7a1bb57c9/views/googleanalytics.js
- https://github.com/mozilla/login.webmaker.org/blob/cdc73720d80ec86d5605d93e4ead9544491bcff6/app/http/views/site/account.html

**Comment by adamlofting** [comment]
Here we go:
- https://github.com/mozilla/make-valet/pull/65
- https://github.com/mozilla/login.webmaker.org/pull/321

**Comment by adamlofting** [comment]
@jbuck now that we're post MWC, can we merge and deploy all of these please?
- https://github.com/mozilla/webmaker.org/pull/1334
- https://github.com/mozilla/popcorn.webmaker.org/pull/594
- https://github.com/mozilla/thimble.webmaker.org/pull/470
- https://github.com/mozilla/webmaker-events-2/pull/237
- https://github.com/mozilla-appmaker/appmaker/pull/2403
- https://github.com/mozilla/goggles.webmaker.org/pull/196
- https://github.com/mozilla/webmaker-landing-pages/pull/129
- https://github.com/mozilla/make-valet/pull/65
- https://github.com/mozilla/login.webmaker.org/pull/321

**Comment by jbuck** [comment]
@adamlofting all done :dancer: :sparkles:

**Comment by adamlofting** [comment]
:boom: :hatched_chick: :boom:

**Comment by adamlofting** [comment]
Actually, reopening, as there are other non-webmaker tasks for me on here still.

**Comment by adamlofting** [comment]
:boat:
